import type { Plugin } from "vite";

// At generateBundle time Vite still names the HTML file as the entry's facade
// (it is rewritten to the script later), so match embed.html, not main.tsx.
export const EMBED_ENTRY_SOURCE = "embed.html";
export const EMBED_LOADER_FILE = "embed/loader.js";

interface ChunkLike {
  type: "chunk" | "asset";
  fileName: string;
  isEntry?: boolean;
  facadeModuleId?: string | null;
  imports?: string[];
  viteMetadata?: { importedCss?: Set<string> };
}

/**
 * A host may sandbox the widget without `allow-same-origin`. Then merely
 * reading `window.localStorage` throws a SecurityError, and editor modules
 * that touch storage at import time crash the whole widget before it can
 * connect. Swap in per-page in-memory storage before anything is imported.
 */
export const STORAGE_SHIM = `for (const name of ["localStorage", "sessionStorage"]) {
  let ok = false;
  try { ok = !!window[name]; } catch {}
  if (!ok) {
    const data = new Map();
    const store = {
      get length() { return data.size; },
      key: (i) => [...data.keys()][i] ?? null,
      getItem: (k) => (data.has(String(k)) ? data.get(String(k)) : null),
      setItem: (k, v) => { data.set(String(k), String(v)); },
      removeItem: (k) => { data.delete(String(k)); },
      clear: () => { data.clear(); },
    };
    Object.defineProperty(window, name, { configurable: true, get: () => store });
  }
}`;

/**
 * Pure part of the plugin: given the finished bundle, produce the source of
 * the fixed-name loader. The MCP Apps resource HTML (served by the backend)
 * can only reference a stable URL, but the entry and its CSS are
 * content-hashed — so the loader is the one un-hashed file, and it injects the
 * hashed CSS/JS at runtime. URLs are derived from the loader's own
 * `import.meta.url` (never the page's location): the loader runs inside a host
 * sandbox on a foreign origin, where a root-relative `/assets/…` would point
 * at the sandbox, not at app.sideform.pro.
 */
export function buildLoaderSource(bundle: Record<string, ChunkLike>): string {
  const entry = Object.values(bundle).find(
    (c) => c.type === "chunk" && c.isEntry && c.facadeModuleId?.replace(/\\/g, "/").endsWith(EMBED_ENTRY_SOURCE),
  );
  if (!entry) throw new Error(`[embed-loader] no entry chunk for ${EMBED_ENTRY_SOURCE} (src/embed/main.tsx)`);

  // CSS reachable from the entry through static imports (the entry chunk's own
  // CSS plus the CSS of shared chunks it pulls in).
  const css = new Set<string>();
  const preload: string[] = [];
  const seen = new Set<string>();
  const walk = (fileName: string) => {
    if (seen.has(fileName)) return;
    seen.add(fileName);
    const chunk = bundle[fileName];
    if (!chunk || chunk.type !== "chunk") return;
    for (const file of chunk.viteMetadata?.importedCss ?? []) css.add(file);
    if (fileName !== entry.fileName) preload.push(fileName);
    for (const dep of chunk.imports ?? []) walk(dep);
  };
  walk(entry.fileName);

  return `// Generated by vite/embedLoader.ts — do not edit. Fixed name, never hashed.
${STORAGE_SHIM}
const base = new URL("../", import.meta.url).href;
globalThis.__SIDEFORM_ASSET_BASE__ = base;
for (const file of ${JSON.stringify([...css])}) {
  const link = document.createElement("link");
  link.rel = "stylesheet";
  link.crossOrigin = "anonymous";
  link.href = new URL(file, base).href;
  document.head.appendChild(link);
}
for (const file of ${JSON.stringify(preload)}) {
  const link = document.createElement("link");
  link.rel = "modulepreload";
  link.crossOrigin = "anonymous";
  link.href = new URL(file, base).href;
  document.head.appendChild(link);
}
await import(new URL(${JSON.stringify(entry.fileName)}, base).href);
`;
}

export function embedLoader(): Plugin {
  return {
    name: "pen-editor:embed-loader",
    apply: "build",
    generateBundle(_options, bundle) {
      this.emitFile({
        type: "asset",
        fileName: EMBED_LOADER_FILE,
        source: buildLoaderSource(bundle as unknown as Record<string, ChunkLike>),
      });
    },
  };
}

/**
 * `renderBuiltUrl` for vite.config.ts: JS-side asset/preload URLs follow the
 * loader-published `__SIDEFORM_ASSET_BASE__` when present (widget), else the
 * usual `base + file`. Only for an absolute-path base; a relative or full-URL
 * base keeps Vite's default (a `base + file` fallback would double the path).
 */
export function embedRenderBuiltUrl(base: string) {
  return (filename: string, { hostType }: { hostType: string }) => {
    if (hostType !== "js" || !base.startsWith("/")) return undefined;
    return {
      runtime: `(globalThis.__SIDEFORM_ASSET_BASE__?new URL(${JSON.stringify(filename)},globalThis.__SIDEFORM_ASSET_BASE__).href:${JSON.stringify(base + filename)})`,
    };
  };
}
